### ISSUE TITLE
Generic MIDI mapping with all inputs and outputs mapped

### ISSUE THREAD

**Issue by gadgetmies** [cmdr-editor/cmdr#6]
Hi,

This is a rather unrelated ask, but as cmdr seems like a quite versatile tool, I was wondering if it could be used to create a .tsi mapping file that would contain all the available Traktor 3 MIDI ins and outs mapped to different MIDI messages? I would need such a file for two purposes:
1) Recording all the MIDI outputs in order to record them and analyse the styles of different DJs or use the recording for macros by playing back the MIDI messages
2) Creating a Ableton Live -style WYSIWYG MIDI mapping tool for Traktor by creating a small app that acts as a proxy between the MIDI device and Traktor and translates the messages in both directions.

I do not have a Windows machine where I could easily try out cmdr, so it would be nice to know if creating such .tsi files is possible before spending a lot of effort to get the application running first.

**Comment by pestrela** [comment]
a) This TSI is necessary for remote control applications like TKFX
https://www.imaginando.pt/products/tkfx-traktor-controller/downloads

b) you can try cmdr on a azure cloud machine very easily, and for free trial:
https://github.com/cmdr-editor/cmdr/blob/master/docs/running_on_macos.md#b-azure-cloud

c) if any commands are missing, they are easy to add using CMDR, but it will be a manual job
to be fully sure the simplest is to do a for loop in the source code in C#.

cheers
